### PR TITLE
add obsolete notice

### PR DESCRIPTION
**Pull request by mikaelarguedas**
Adding this notice rather than deleting the repository mostly because the [beta2 turtlebot repos file](https://github.com/ros2/turtlebot2_demo/blob/release-latest/turtlebot2_demo.repos) includes this repo.

Alternatives:
- Delete the repo anyway without changing the repos file:
  - :disappointed:  users will have an error message on `vcs import` but could still build and run the demo
- Delete the repo and modified the tagged repo file:
  - :smile:  no error message when importing, less confusing for users
  - :angry:   Changing a tagged file

### CODE REVIEW

**Review by dirk-thomas — APPROVED** [review]

**Comment by tfoote** [comment]
Option 3. Keep the README change as proposed. And delete all other content from the default branch. Anyone who still has the default branch in their checkout will update to have no content. And all tags and branches will still be available for older checkouts.

Potential followup, is to move the repo to a ros2-retired organization. And rely on github redirects to keep old repo files alive.

**Comment by mikaelarguedas** [comment]
That's a good point, I like option 3. @ros2/team any preference on this ?

**Comment by clalancette** [comment]
Yeah, I like the idea of deleting the content from the default branch.  I've done that in the past and it has worked well.  I'm fine either way whether we want to move this to a "ros2-retired" organization or not.

**Comment by dirk-thomas** [comment]
I am agnostic to deleting all content but the README from the default branch. Whatever is done should also be applied to other repos like `gmock_vendor`, `gtest_vendor`.

Since we have tabled the decision where to place various repos I would argue that we should also delay any potential moves to `ros2-retired`. I don't expect that we have to host Beta 2 "forever" and that we can likely remove the repos in the near future.

**Comment by mikaelarguedas** [comment]
> I am agnostic to deleting all content but the README from the default branch. Whatever is done should also be applied to other repos like gmock_vendor, gtest_vendor.

Good point, if everybody is ok with that I'll open a similar set of PRs on these repos.

>  I don't expect that we have to host Beta 2 "forever" and that we can likely remove the repos in the near future.

Yeah I agree with this, I don't think anything preceding "1.0" should be kept around for legacy purposes except what is used for the latest release.

**Review by tfoote — APPROVED** [review]

**Pull request merged**
